version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: kindle_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: kindle_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 